//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int Animal_Id { get; set; }
        public string Animal_Name { get; set; }
        public string Animal_Sex { get; set; }
        public int Animal_ShopId { get; set; }
        public int Animal_CageId { get; set; }
        public int Animal_SpeciesId { get; set; }
        public System.DateTime Animal_Date { get; set; }
        public Nullable<int> Animal_ColorId { get; set; }
        public int Animal_Price { get; set; }
    
        public virtual Cage Cage { get; set; }
        public virtual Color Color { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual Species Species { get; set; }
    }
}
