//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeciesFood
    {
        public int SpeciesFood_Id { get; set; }
        public int Species_Id { get; set; }
        public int Food_Id { get; set; }
    
        public virtual Food1 Food1 { get; set; }
        public virtual Species Species { get; set; }
    }
}
